//User Reducer Types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';
//UI REDUCER TYPES
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';
//DATA REDUCER TYPES
export const SET_SCREAMS = 'SET_SCREAMS';
export const SET_SCREAM = 'SET_SCREAM';
export const UPVOTE_SCREAM = 'UPVOTE_SCREAM';
export const DOWNVOTE_SCREAM = 'DOWNVOTE_SCREAM';
export const DELETE_SCREME = 'DELETE_SCREME';
export const POST_SCREAM = 'POST_SCREAM';
export const UPDATE_POST = 'UPDATE_POST';
